version: "3.9"
services:
  frontend:
    build: ./frontend/
    ports:
      - "3000:3000"
    networks:
      - pub-sub-oracle-network
  server:
    build: .
    ports:
      - "8080:8080"
    networks: 
      - pub-sub-oracle-network

networks:
    pub-sub-oracle-network:
        name: pub-sub-oracle-network